quotes = {
    "Love": [
        {"text": "Love is composed of a single soul inhabiting two bodies.", "author": "Aristotle"},
        {"text": "To love and be loved is to feel the sun from both sides.", "author": "David Viscott"},
        {"text": "Love is a friendship set to music.", "author": "Joseph Campbell"},
        {"text": "Being deeply loved by someone gives you strength.", "author": "Lao Tzu"},
        {"text": "We accept the love we think we deserve.", "author": "Stephen Chbosky"},
        {"text": "Love recognizes no barriers.", "author": "Maya Angelou"},
        {"text": "Where there is love there is life.", "author": "Mahatma Gandhi"},
        {"text": "Love is the flower you've got to let grow.", "author": "John Lennon"},
        {"text": "Love cures people—both the ones who give it and the ones who receive it.", "author": "Karl Menninger"},
        {"text": "The best thing to hold onto in life is each other.", "author": "Audrey Hepburn"},
        {"text": "Love doesn’t make the world go ‘round. Love is what makes the ride worthwhile.", "author": "Franklin P. Jones"},
        {"text": "You always gain by giving love.", "author": "Reese Witherspoon"},
        {"text": "Love is not about how many days, months, or years you have been together. It’s about how much you love each other every day.", "author": "Unknown"},
        {"text": "In dreams and in love there are no impossibilities.", "author": "János Arany"},
        {"text": "Love is when the other person's happiness is more important than your own.", "author": "H. Jackson Brown Jr."},
        {"text": "The giving of love is an education in itself.", "author": "Eleanor Roosevelt"},
        {"text": "True love stories never have endings.", "author": "Richard Bach"},
        {"text": "Love does not dominate; it cultivates.", "author": "Johann Wolfgang von Goethe"},
        {"text": "To love is nothing. To be loved is something. But to love and be loved, that’s everything.", "author": "T. Tolis"},
        {"text": "Love is the whole thing. We are only pieces.", "author": "Rumi"}
    ],

    "Life": [
        {"text": "Life is what happens when you're busy making other plans.", "author": "John Lennon"},
        {"text": "The purpose of our lives is to be happy.", "author": "Dalai Lama"},
        {"text": "Get busy living or get busy dying.", "author": "Stephen King"},
        {"text": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
        {"text": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
        {"text": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
        {"text": "Life is made of ever so many partings welded together.", "author": "Charles Dickens"},
        {"text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey"},
        {"text": "Life is short, and it is up to you to make it sweet.", "author": "Sarah Louise Delany"},
        {"text": "Difficult and meaningful will always bring more satisfaction than easy and meaningless.", "author": "Maxime Lagacé"},
        {"text": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi"},
        {"text": "In the end, we only regret the chances we didn’t take.", "author": "Lewis Carroll"},
        {"text": "The biggest adventure you can take is to live the life of your dreams.", "author": "Oprah Winfrey"},
        {"text": "Life is trying things to see if they work.", "author": "Ray Bradbury"},
        {"text": "Live life to the fullest and focus on the positive.", "author": "Matt Cameron"},
        {"text": "Life is like riding a bicycle. To keep your balance, you must keep moving.", "author": "Albert Einstein"},
        {"text": "My life is my message.", "author": "Mahatma Gandhi"},
        {"text": "A happy life is one spent in learning, earning, and yearning.", "author": "Lillian Gish"},
        {"text": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller"},
        {"text": "Life isn't about finding yourself. It's about creating yourself.", "author": "George Bernard Shaw"}
    ],

    "Motivation": [
        {"text": "The harder you work for something, the greater you’ll feel when you achieve it.", "author": "Unknown"},
        {"text": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
        {"text": "Push yourself, because no one else is going to do it for you.", "author": "Unknown"},
        {"text": "Great things never come from comfort zones.", "author": "Roy T. Bennett"},
        {"text": "Dream it. Wish it. Do it.", "author": "Unknown"},
        {"text": "Success doesn’t just find you. You have to go out and get it.", "author": "Unknown"},
        {"text": "The harder the battle, the sweeter the victory.", "author": "Les Brown"},
        {"text": "Don’t stop when you’re tired. Stop when you’re done.", "author": "Marilyn Monroe"},
        {"text": "Wake up with determination. Go to bed with satisfaction.", "author": "George Lorimer"},
        {"text": "Do something today that your future self will thank you for.", "author": "Sean Patrick Flanery"},
        {"text": "Little things make big days.", "author": "Isabel Marant"},
        {"text": "It’s going to be hard, but hard does not mean impossible.", "author": "Art Williams"},
        {"text": "Don’t wait for opportunity. Create it.", "author": "George Bernard Shaw"},
        {"text": "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", "author": "Unknown"},
        {"text": "The key to success is to focus on goals, not obstacles.", "author": "Unknown"},
        {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
        {"text": "Doubt kills more dreams than failure ever will.", "author": "Suzy Kassem"},
        {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
        {"text": "Stay hungry. Stay foolish.", "author": "Steve Jobs"},
        {"text": "You are stronger than you think.", "author": "Unknown"}
    ],

    "Success": [
        {"text": "Success is not in what you have, but who you are.", "author": "Bo Bennett"},
        {"text": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
        {"text": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller"},
        {"text": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson"},
        {"text": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill"},
        {"text": "Opportunities don't happen. You create them.", "author": "Chris Grosser"},
        {"text": "Don't let the fear of losing be greater than the excitement of winning.", "author": "Robert Kiyosaki"},
        {"text": "If you really look closely, most overnight successes took a long time.", "author": "Steve Jobs"},
        {"text": "Success is not in what you accomplish in your life, but what you inspire others to do.", "author": "Unknown"},
        {"text": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis"},
        {"text": "Success is getting what you want, happiness is wanting what you get.", "author": "W. P. Kinsella"},
        {"text": "I never dreamed about success. I worked for it.", "author": "Estee Lauder"},
        {"text": "Success is how high you bounce when you hit bottom.", "author": "George S. Patton"},
        {"text": "The secret of success is to do the common thing uncommonly well.", "author": "John D. Rockefeller Jr."},
        {"text": "Success is liking yourself, liking what you do, and liking how you do it.", "author": "Maya Angelou"},
        {"text": "The difference between success and failure is the ability to take action.", "author": "Alexander Graham Bell"},
        {"text": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill"},
        {"text": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon"},
        {"text": "Try not to become a person of success, but rather try to become a person of value.", "author": "Albert Einstein"},
        {"text": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier"}
    ],

    "Friendship": [
        {"text": "Friendship is the only cement that will ever hold the world together.", "author": "Woodrow Wilson"},
        {"text": "A real friend is one who walks in when the rest of the world walks out.", "author": "Walter Winchell"},
        {"text": "Friendship is always a sweet responsibility, never an opportunity.", "author": "Khalil Gibran"},
        {"text": "Friends are the family you choose.", "author": "Jess C. Scott"},
        {"text": "A friend is someone who knows all about you and still loves you.", "author": "Elbert Hubbard"},
        {"text": "True friendship comes when the silence between two people is comfortable.", "author": "David Tyson Gentry"},
        {"text": "Friends are the siblings God never gave us.", "author": "Mencius"},
        {"text": "A single rose can be my garden... a single friend, my world.", "author": "Leo Buscaglia"},
        {"text": "Friendship improves happiness and abates misery.", "author": "Cicero"},
        {"text": "Walking with a friend in the dark is better than walking alone in the light.", "author": "Helen Keller"},
        {"text": "Friendship is the golden thread that ties the heart of all the world.", "author": "John Evelyn"},
        {"text": "There are no strangers here; Only friends you haven’t yet met.", "author": "William Butler Yeats"},
        {"text": "Friendship is like a sheltering tree.", "author": "Samuel Taylor Coleridge"},
        {"text": "It’s not what we have in life, but who we have in our life that matters.", "author": "Unknown"},
        {"text": "Some people go to priests; others to poetry; I to my friends.", "author": "Virginia Woolf"},
        {"text": "Friendship multiplies the good of life and divides the evil.", "author": "Baltasar Gracian"},
        {"text": "Friends are the most important ingredient in this recipe of life.", "author": "Unknown"},
        {"text": "Friendship is a strong and habitual inclination in two persons to promote the good and happiness of one another.", "author": "Eustace Budgell"},
        {"text": "The language of friendship is not words but meanings.", "author": "Henry David Thoreau"},
        {"text": "A true friend is the greatest of all blessings.", "author": "Francesco Petrarca"}
    ],

    "Health": [
        {"text": "Take care of your body. It's the only place you have to live.", "author": "Jim Rohn"},
        {"text": "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "author": "Buddha"},
        {"text": "A healthy outside starts from the inside.", "author": "Robert Urich"},
        {"text": "Your body deserves the best.", "author": "Unknown"},
        {"text": "Happiness is nothing more than good health and a bad memory.", "author": "Albert Schweitzer"},
        {"text": "It is health that is real wealth and not pieces of gold and silver.", "author": "Mahatma Gandhi"},
        {"text": "Good health is true wealth.", "author": "Unknown"},
        {"text": "To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear.", "author": "Buddha"},
        {"text": "Health is a state of complete harmony of the body, mind, and spirit.", "author": "B.K.S. Iyengar"},
        {"text": "The greatest wealth is health.", "author": "Virgil"},
        {"text": "A healthy attitude is contagious but don’t wait to catch it from others.", "author": "Tom Stoppard"},
        {"text": "Without health life is not life; it is only a state of languor and suffering.", "author": "Rabelais"},
        {"text": "Happiness is the highest form of health.", "author": "Dalai Lama"},
        {"text": "Good health and good sense are two of life’s greatest blessings.", "author": "Publilius Syrus"},
        {"text": "Early to bed and early to rise makes a man healthy, wealthy, and wise.", "author": "Benjamin Franklin"},
        {"text": "Health is the first muse, and sleep is the condition to produce it.", "author": "Ralph Waldo Emerson"},
        {"text": "The doctor of the future will give no medicine but will interest his patients in the care of the human frame.", "author": "Thomas Edison"},
        {"text": "Take care of your body; it’s the only place you have to live.", "author": "Jim Rohn"},
        {"text": "A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.", "author": "Naval Ravikant"},
        {"text": "To enjoy the glow of good health, you must exercise.", "author": "Gene Tunney"}
    ],

    "Happiness": [
        {"text": "Happiness depends upon ourselves.", "author": "Aristotle"},
        {"text": "For every minute you are angry you lose sixty seconds of happiness.", "author": "Ralph Waldo Emerson"},
        {"text": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama"},
        {"text": "Happiness is when what you think, what you say, and what you do are in harmony.", "author": "Mahatma Gandhi"},
        {"text": "The purpose of our lives is to be happy.", "author": "Dalai Lama"},
        {"text": "Happiness is a warm puppy.", "author": "Charles M. Schulz"},
        {"text": "Count your age by friends, not years. Count your life by smiles, not tears.", "author": "John Lennon"},
        {"text": "Happiness is not by chance, but by choice.", "author": "Jim Rohn"},
        {"text": "Happiness is the secret to all beauty. There is no beauty without happiness.", "author": "Christian Dior"},
        {"text": "The only joy in the world is to begin.", "author": "Cesare Pavese"},
        {"text": "Happiness is only real when shared.", "author": "Christopher McCandless"},
        {"text": "Most folks are as happy as they make up their minds to be.", "author": "Abraham Lincoln"},
        {"text": "Happiness is a state of activity.", "author": "Aristotle"},
        {"text": "Happiness is a perfume you cannot pour on others without getting a few drops on yourself.", "author": "Ralph Waldo Emerson"},
        {"text": "True happiness is... to enjoy the present, without anxious dependence upon the future.", "author": "Seneca"},
        {"text": "Happiness is the natural flower of duty.", "author": "Phillips Brooks"},
        {"text": "Happiness is not having what you want. It is appreciating what you have.", "author": "Unknown"},
        {"text": "Happiness is the highest good.", "author": "Aristotle"},
        {"text": "Happiness is a habit – cultivate it.", "author": "Elbert Hubbard"},
        {"text": "Happiness is when you feel good about yourself and your life.", "author": "Unknown"}
    ],

    "Wisdom": [
        {"text": "The only true wisdom is in knowing you know nothing.", "author": "Socrates"},
        {"text": "Turn your wounds into wisdom.", "author": "Oprah Winfrey"},
        {"text": "Knowing yourself is the beginning of all wisdom.", "author": "Aristotle"},
        {"text": "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", "author": "Albert Einstein"},
        {"text": "The fool doth think he is wise, but the wise man knows himself to be a fool.", "author": "Shakespeare"},
        {"text": "The invariable mark of wisdom is to see the miraculous in the common.", "author": "Ralph Waldo Emerson"},
        {"text": "Turn your pain into wisdom.", "author": "Unknown"},
        {"text": "Wisdom is the reward you get for a lifetime of listening when you would rather have talked.", "author": "Doug Larson"},
        {"text": "Wisdom is knowing what to do next; virtue is doing it.", "author": "David Starr Jordan"},
        {"text": "Wisdom is the power to put our time and our knowledge to the proper use.", "author": "Thomas J. Watson"},
        {"text": "Wisdom comes from experience.", "author": "Unknown"},
        {"text": "The wise man does at once what the fool does finally.", "author": "Niccolò Machiavelli"},
        {"text": "Wisdom begins in wonder.", "author": "Socrates"},
        {"text": "Knowledge speaks, but wisdom listens.", "author": "Jimi Hendrix"},
        {"text": "Wisdom is knowing the right path to take. Integrity is taking it.", "author": "M.H. McKee"},
        {"text": "Wisdom is the daughter of experience.", "author": "Leonardo da Vinci"},
        {"text": "Wisdom is the sunlight of the soul.", "author": "German Proverb"},
        {"text": "Wisdom is oftentimes nearer when we stoop than when we soar.", "author": "William Wordsworth"},
        {"text": "Wisdom is nothing more than healed pain.", "author": "Robert Greene"},
        {"text": "Wisdom is avoiding all thoughts that weaken you.", "author": "Wayne Dyer"}
    ],

    "Inspirational": [
        {"text": "Act as if what you do makes a difference. It does.", "author": "William James"},
        {"text": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs"},
        {"text": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
        {"text": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar"},
        {"text": "Dream big and dare to fail.", "author": "Norman Vaughan"},
        {"text": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis"},
        {"text": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
        {"text": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe"},
        {"text": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman"},
        {"text": "It always seems impossible until it’s done.", "author": "Nelson Mandela"},
        {"text": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer"},
        {"text": "The best way to predict the future is to create it.", "author": "Abraham Lincoln"},
        {"text": "Don’t let what you cannot do interfere with what you can do.", "author": "John Wooden"},
        {"text": "Everything you’ve ever wanted is on the other side of fear.", "author": "George Addair"},
        {"text": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis"},
        {"text": "Believe in yourself and all that you are.", "author": "Christian D. Larson"},
        {"text": "Do not wait to strike till the iron is hot; but make it hot by striking.", "author": "William Butler Yeats"},
        {"text": "Great minds discuss ideas; average minds discuss events; small minds discuss people.", "author": "Eleanor Roosevelt"},
        {"text": "Everything has beauty, but not everyone sees it.", "author": "Confucius"},
        {"text": "Keep going. Everything you need will come to you at the perfect time.", "author": "Unknown"}
    ]
}
